/*
	This directory contains functions that generate Solidity code.
*/

import ts from "typescript";
import { CodeGenerator, NodeHandler } from "..";
import { classHandler } from "./class";

export interface SolidityGenerator extends CodeGenerator {
  code: string;
}

export function createSolidityGenerator(): SolidityGenerator {
  return {
    getDefaultHandlerMap() {
      return {
        ...classHandler,
      };
    },
    print() {
      return this.code;
    },
    code: `// This file was generated by Vallum.
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

`,
  };
}

export function createSolidityHandler<TNode extends ts.Node>({
  syntaxKind,
  handler,
}: {
  syntaxKind: ts.SyntaxKind;
  handler: NodeHandler<SolidityGenerator, TNode>;
}) {
  return {
    [syntaxKind]: handler,
  };
}
